spring.application.name=charcuterie-orders

spring.datasource.url=jdbc:postgresql://localhost:5432/charcuterie
spring.datasource.username=char_user
spring.datasource.password=char_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.session.timeout=12h